### ISSUE TITLE
RelationshipsValidator::checkKey($key) doesn't check if key is allowed

### ISSUE THREAD

**Issue by danielebriggi** [cloudcreativity/json-api#20]
Differently to what is done in `AttributesValidator::checkKey()`, the same method in `RelationshipsValidator` class doesn't check if the key is allowed.

I whould fix the `checkKey()` as follow in the `RelationshipsValidator`:

```
protected function checkKey($key)
{
    if (!$this->hasValidator($key) || !$this->isAllowedKey($key)) {
        $this->error(static::ERROR_UNRECOGNISED_RELATIONSHIP)
            ->source()
            ->setPointer(sprintf('/%s', $key));
    }

    return $this;
}
```

**Comment by danielebriggi** [comment]
Sorry, it's already fixed in the _develop_ branch

```
protected function checkKey($key)
{
    if (!$this->isAllowedKey($key)) {
        $this->error(static::ERROR_UNRECOGNISED_RELATIONSHIP)
            ->getSourceObject()
            ->setPointer(sprintf('/%s', $key));
    }
    return $this;
}
```

**Comment by lindyhopchris** [comment]
@danielebriggi 

Thanks for taking the time to report this. (Sorry for slow reply - not been keeping up with stuff over the Xmas/New Year period).

I'm planning to merge develop into master and tag the next version (v0.4.0) later in January, so that's when you'll be able to get access to this fix on a tagged version.
