### ISSUE TITLE
Pagination on relationships

### ISSUE THREAD

**Issue by Davidepaalte** [cloudcreativity/json-api#41]
In the _User/Posts_ example:
Imagine I want to present the User all his Posts.
I could `return $user->posts`, but there are lots of posts for each user, so I want to paginate them.

From my research, there is nothing like this available in laravel. (If there is, please let me know!)
I think it would be a really good feature if it's not planned yet.

**Comment by lindyhopchris** [comment]
Hi!

In Laravel, `$user->posts()->paginate()` would return a the paginated posts for that user. Any method that is available on the database query builder is available on the relation (i.e. the class that is returned by the `posts()` method).

In our `cloudcreativity/laravel-json-api` package we have support for paginating relationships on our `1.0.0-alpha.1` branch, so that will be available when that is turned into a tagged release. This means you'd be able to do: `GET /users/1/posts?page[number]=1&page[size]=15` and get a paginated response.
